### PR TITLE
fix independency of Cray toolchains w.r.t. toolchain build environment

### PR DESCRIPTION
**Pull request by boegel**
fix for bug reported in #1636 by @gppezzi

### CODE REVIEW

**Comment by boegel** [comment]
@pforai: please review?

**Comment by pforai** [comment]
Good catch aktuelly! Merge now! :)

**Comment by boegel** [comment]
I'm looking into a cleaner fix, the `deepcopy` feels to much like dancing around the problem...

**Comment by boegel** [comment]
Hmm, nevermind, the alternate solution I have in mind is way worse... :D

Going in, thanks for the review @pforai!

**Pull request merged**
