### PR TITLE
avoid that fancylogger tries to import mpi4py to determine MPI rank

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@stdweird: there's no other way right (and this is quite OK imho)

cc @pforai, @gppezzi

**Comment by pforai** [comment]
It has to happen before importing as far as I understand it and that is quite a simple solution.

**Comment by gppezzi** [comment]
:+1:

**Comment by stdweird** [comment]
not an easy way, no. in  principle, it should only be set on system with broken mpi4py, but i guess there's no harm in disabling it like this for EB.

**Comment by boegel** [comment]
I agree @stdweird, no harm done with disabling this for EB.

Going in, thanks for the feedback everyone!

**Pull request merged**
