### PR TITLE
fix --dep-graph, use all_dependencies EasyConfig class variable rather than 'dependencies' parameter

### PR DESCRIPTION
**Pull request by boegel**
fix for bug introduced in #1356, see also https://github.com/hpcugent/easybuild-easyconfigs/pull/1870

### CODE REVIEW

**Comment by boegel** [comment]
This needs a unit test to catch that bug...

**Comment by boegel** [comment]
@wpoely86, @pforai, @rjeschmi: please review?

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
