### PR TITLE
Add cuda 7.0 entry for the version available on Titan.

### PR DESCRIPTION
**Pull request by uhaehner**

### CODE REVIEW

**Comment by gppezzi** [comment]
lgtm 

thanks @uhaehner !

**Comment by boegel** [comment]
Jenkins: ok to test

(good to go when Jenkins gives green light, although there's very little that can go wrong here :-))

**Comment by boegel** [comment]
Ah, hold on...

@uhaehner: Please open the PR to `develop` rather than `master`...

**Comment by boegel** [comment]
replaced with #1721, thanks @uhaehner

**Pull request closed without merging**
