### PR TITLE
rework module_generator to avoid keeping state w.r.t. fake modules

### PR DESCRIPTION
**Pull request by boegel**
fix (+ enhanced unit test) for #1329, reported by @dirkdedraak and @rjeschmi

### CODE REVIEW

**Comment by boegel** [comment]
@rjeschmi: up for reviewing this? maybe @pforai can take a look too, since he has played around in `module_generator.py` quite a bit in the past

**Comment by rjeschmi** [comment]
Yeah, this is generally what I thought needed to be done (but didn't really know how to do). Most of the state information wasn't helpful and was ripe for side-effects.

I'll try testing it, but otherwise looks good.

**Comment by rjeschmi** [comment]
tested it and it seems to work fine with packaging.

**Comment by JensTimmerman** [comment]
ok

**Comment by boegel** [comment]
Thanks for the reviewing/testing @rjeschmi and @JensTimmerman!

**Pull request merged**
