### PR TITLE
add 'rpath' toolchain option to selectively disable use of RPATH wrappers

### PR DESCRIPTION
**Pull request by boegel**
@pescobar this probably works, but needs to be tested. Can you give it a try?

I'll also look into a dedicated test for this.

### CODE REVIEW

**Comment by boegel** [comment]
included tests indicate that this works as intended, so I'll go ahead and merge this to include it in the upcoming EasyBuild v3.0.2 (I consider not being able to selectively disable use of RPATH a bug, so this is a bug fix).

@pescobar let us know whether this works as expected for you when you find the time for it

**Comment by pescobar** [comment]
this seems to have an issue. see this build log
https://gist.github.com/anonymous/1304396c16272fd789595ea558ee52bc

I have enabled this option:
https://gist.github.com/anonymous/1304396c16272fd789595ea558ee52bc#file-file1-txt-L46

But still the rpath sanity check is applied:
https://gist.github.com/anonymous/1304396c16272fd789595ea558ee52bc#file-file1-txt-L2946

**Comment by boegel** [comment]
@pescobar urgh, indeed, the RPATH sanity check should of course also be checked if no RPATH'ing was done...

Try this patch?

```diff
diff --git a/easybuild/framework/easyblock.py b/easybuild/framework/easyblock.py
index dbce5c3..8aa5cb3 100644
--- a/easybuild/framework/easyblock.py
+++ b/easybuild/framework/easyblock.py
@@ -1982,7 +1982,7 @@ class EasyBlock(object):
         else:
             self.dry_run_msg("  (none)")
 
-        if build_option('rpath'):
+        if build_option('rpath') and self.toolchain.options.get('rpath', True):
             self.sanity_check_rpath()
 
     def _sanity_check_step(self, custom_paths=None, custom_commands=None, extension=False):

```

**Comment by pescobar** [comment]
@boegel this patch doesn't seem to work
https://gist.github.com/anonymous/b1b63fb80ead6418a41c59126f7e6677#file-file1-txt-L2946

```
[easybuild@compilator easyconfigs]$ sed '1985q;d' $EBROOTEASYBUILD/lib/python2.6/site-packages/easybuild_framework-3.0.1-py2.6.egg/easybuild/framework/easyblock.py
        if build_option('rpath') and self.toolchain.options.get('rpath', True):
```

**Comment by boegel** [comment]
@pescobar I only patched the `sanity_check_dry_run` (which is only used under `-x`)...

Try this (I'll open a PR with a proper fix in a bit):

```diff
diff --git a/easybuild/framework/easyblock.py b/easybuild/framework/easyblock.py
index dbce5c3..49c2290 100644
--- a/easybuild/framework/easyblock.py
+++ b/easybuild/framework/easyblock.py
@@ -1982,7 +1982,8 @@ class EasyBlock(object):
         else:
             self.dry_run_msg("  (none)")
 
-        if build_option('rpath'):
+        print self.toolchain.options
+        if build_option('rpath') and self.toolchain.options.get('rpath', True):
             self.sanity_check_rpath()
 
     def _sanity_check_step(self, custom_paths=None, custom_commands=None, extension=False):
@@ -2051,7 +2052,7 @@ class EasyBlock(object):
         if fake_mod_data:
             self.clean_up_fake_module(fake_mod_data)
 
-        if build_option('rpath'):
+        if build_option('rpath') and self.toolchain.options.get('rpath', True):
             rpath_fails = self.sanity_check_rpath()
             if rpath_fails:
                 self.log.warning("RPATH sanity check failed!")

```

**Comment by boegel** [comment]
@pescobar proper fix + test that catches the bug in #2052

**Pull request merged**
