### PR TITLE
enhance bootstrap to auto-skip stage 0 in case a suitable setuptools is already available

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@riccardomurri up for testing this (w.r.t. #1887)?

**Comment by riccardomurri** [comment]
Installation failed on a (almost) vanilla Ubuntu 16.04::

    ubuntu@eb-test:~$ wget https://raw.githubusercontent.com/boegel/easybuild-framework/auto_skip_stage0_bootstrap/easybuild/scripts/bootstrap_eb.py
    ...
    2016-10-14 08:48:40 (1.40 MB/s) - 'bootstrap_eb.py' saved [41578/41578]

    ubuntu@eb-test:~$ sudo apt install lmod
    ...
    Setting up lmod (5.8-1) ...
    Processing triggers for libc-bin (2.23-0ubuntu3) ...

    ubuntu@eb-test:~$ source /usr/share/lmod/lmod/init/bash

    ubuntu@eb-test:~$ python bootstrap_eb.py $HOME/easybuild
    [[INFO]] EasyBuild bootstrap script (version 20161006.01, MD5: c91bf277b86f693463f05119f068e4de)
    [[INFO]] Found Python 2.7.12 (default, Jul  1 2016, 15:12:24) ; [GCC 5.4.0 20160609]

    [[INFO]] Installation prefix /home/ubuntu/easybuild
    [[INFO]] Found module command '/usr/share/lmod/lmod/libexec/lmod' via $LMOD_CMD (Lmod), so using it.
    [[INFO]] No suitable setuptools installation found, proceeding with stage 0...


    [[INFO]] +++ STAGE 0: installing distribute via included (patched) distribute_setup.py...

    Downloading http://hpcugent.github.io/easybuild/files/distribute-0.6.49-patched1.tar.gz
    Extracting in /tmp/tmpTHecFs
    Now working in /tmp/tmpTHecFs/distribute-0.6.49
    Installing Distribute
    [[INFO]] Installed setuptools version 0.6 (/tmp/tmpMEOFQY/lib/python2.7/site-packages/distribute-0.6.49-py2.7.egg/setuptools/__init__.pyc)


    [[INFO]] +++ STAGE 1: installing EasyBuild in temporary dir with easy_install...

    [[INFO]] installing EasyBuild with 'easy_install --quiet --upgrade --prefix=/tmp/tmpMEOFQY/eb_stage1 easybuild'
    [[INFO]] running post install command 'easy_install --upgrade --prefix=/tmp/tmpMEOFQY/eb_stage1 vsc-base'
    [[ERROR]] Failed to find right 'easy_install' command!

The starting VM image is a Ubuntu 16.04 with the `python` package installed
(which is not in the default base image; only `python3` is).

**Comment by boegel** [comment]
@riccardomurri can you upload to debug output (`EASYBUILD_BOOTSTRAP_DEBUG=1 python bootstrap_eb.py ...`) to a gist?

**Comment by riccardomurri** [comment]
Same results on Ubuntu 14.04, with the addition that `git` is required (see https://github.com/hpcugent/easybuild-framework/issues/1962)

**Comment by riccardomurri** [comment]
@boegel here's the DEBUG log of the Ubuntu 14.04 failure: 
https://gist.github.com/riccardomurri/a5c803f820cba43a8300e1c19e629faa

**Comment by riccardomurri** [comment]
@boegel here's the DEBUG log of the Ubuntu 14.04 failure: 
https://gist.github.com/riccardomurri/a5c803f820cba43a8300e1c19e629faa

**Comment by boegel** [comment]
@riccardomurri Urgh, I indeed missing something... Please try again?

**Comment by boegel** [comment]
@riccardomurri ping on retesting this?

**Comment by boegel** [comment]
OK, I think this is good to go, it has been tested extensively in various contexts:

* my laptop (OS X)
* the OpenHPC build service where it does an offline install, cfr. https://build.openhpc.community/package/show/home:boegel/easybuild
* an Arch Linux system that has Python3 as default Python (requires `python2 bootstrap_.eb.py $PREFIX`)

I would like to also verify that the offline install mode doesn't get broken in Travis, but I'll do that in a follow-up PR.

Thanks for all the feedback on this @riccardomurri!

**Pull request merged**
