### PR TITLE
add support for running Lmod in debug mode

### PR DESCRIPTION
**Pull request by boegel**
TODO:

* [x] dedicated tests for `--lmod-debug`
* [x] rename to `--debug-lmod`?

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86 please review

also: `--lmod-debug` or `--debug-lmod`?

**Comment by boegel** [comment]
renamed option to `--debug-lmod` (makes more sense to me), added dedicated test, should be good to go now, @wpoely86?

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
