### PR TITLE
Question answer

### PR DESCRIPTION
**Pull request by npklein**
Part of adding question/answer  functionallity during command line installation to install Anaconda

### CODE REVIEW

**Comment by boegel** [comment]
@npklein: I'm not sure this is the right location for this (the `qa` variable you're adding), since you need a way to tie this to a particular call to `run_cmd(_qa)`.
What you really need, I think, is to add a custom easyconfig parameter for the Binary easyblock (in `extra_options`, see https://github.com/hpcugent/easybuild-easyblocks/blob/master/easybuild/easyblocks/generic/binary.py#L53), and then use that value in the `run_cmd` calling in `Binary.install_step` (at https://github.com/hpcugent/easybuild-easyblocks/blob/master/easybuild/easyblocks/generic/binary.py#L109).

It's also not clear what impact the changes have to `run_cmd_qa`, we need to be very careful here not to break anything that works...

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@npklein: ping on this?

**Comment by npklein** [comment]
@boegel did not manage to get this finished

**Comment by boegel** [comment]
@npklein: I'm just wondering whether it makes sense at all, see remarks above

**Pull request closed without merging**
