### PR TITLE
fix fetch_easyconfigs_from_pr w.r.t. duplicate files in PRs

### PR DESCRIPTION
**Pull request by boegel**
some PRs include files with the same name in multiple places (e.g. patch files)

example: https://github.com/hpcugent/easybuild-easyconfigs/pull/2546

This fix makes sure that `--from-pr` can deal with it.

### CODE REVIEW

**Comment by wpoely86** [comment]
lgtm

**Comment by ocaisa** [comment]
As an aside, the first time I saw lgtm used in PRs (some months ago), I didn't know what it meant so I googled it...until this week, as advised by the urban slang dictionary, I believed it meant "Let's get this money"

**Comment by boegel** [comment]
@ocaisa: There's no money involved here, this is FOSS. :P

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
