### PR TITLE
work towards enforcing availability of SHA256 checksums for all sources/patches

### PR DESCRIPTION
**Pull request by boegel**
This PR makes a couple of changes:

* also support `sha256` and `sha512` as checksum types
* auto-detect MD5 vs SHA256 checksums when no checksum type is specified (based on length of provided checksum)
* report both MD5 and SHA256 checksums in log for all sources/patches (incl. extensions)
* add `--enforce-checksums` option to enforce presence of checksums for all sources/patches

It's a first step towards having SHA256 checksums for all sources/patches in all centrally provided easyconfigs.

### CODE REVIEW

**Comment by ocaisa** [comment]
We could also add the checksums automatically to the archived easyconfig

**Comment by boegel** [comment]
@ocaisa Sure, but I think that should be done in a separate PR, since that's a bit fiddly (you need to inject `checksums =`, preferably under `sources = `...)

Also, there's a bit of chicken-egg situation there, I think, especially if we want to add SHA256 checksums automatically, i.e. they could only be consumed with an EasyBuild version that includes support for (auto-detection of) SHA256 checksums...

**Comment by vanzod** [comment]
This PR seems good to me. Nice work

**Comment by boegel** [comment]
Thanks for the review @wpoely86 and @vanzod!

**Pull request merged**
