### PR TITLE
fix generate_software_list.py script

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
merging in as trivial

**Comment by boegel** [comment]
or hmm, hold on, why didn't the unit test for this script catch that it's broken?!

**Comment by boegel** [comment]
unit tests didn't catch this because none of the test easyconfigs includes a dependency marked as an external module, fixing that...

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Thanks @wpoely86 for the review!

**Pull request merged**
