### PR TITLE
stop including a crippled copy of vsc-base, include vsc-base as a proper dependency instead

### PR DESCRIPTION
**Pull request by boegel**
depends on https://github.com/hpcugent/vsc-base/pull/153 and a vsc-base v2.0.1 release on PyPi

@stdweird: please review

### CODE REVIEW

**Comment by wpoely86** [comment]
looks fine?

**Comment by boegel** [comment]
Once https://github.com/hpcugent/vsc-base/pull/153 is merged in, this meeds extensive testing to see whether installing this eith easy_install and the bootstrap script still works as expected.

I hope to get this out soon, since we would have an early alpha

**Comment by stdweird** [comment]
LGTM, but test failed
i guess you need to give jenkins the new dependency first?

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
@stdweird: yep, vsc-base is installed on Jenkins (and reinstalled whenever a vsc-base PR is merged in), but the EasyBuild framework tests did not have the location included in `$PYTHONPATH` yet, should be fixed now for the PR building test

**Comment by boegel** [comment]
@wpoely86: feel like playing around with this, e.g. testing it with `easy_install` and/or `pip`, and see if anything breaks?

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
for some reason, Jenkins can't obtain a GitHub token anymore for the unit tests that require it... not sure what's going on there, will look into fixing it

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
issues with GitHub token used by Jenkins fixed via #1165

**Comment by wpoely86** [comment]
```
$ easy_install --prefix $HOME/opt https://github.com/boegel/easybuild-framework/archive/fd142036749d30e7f088e0f84eaff9cb0929ff50.tar.gz#egg=easybuild-frameworkDownloading https://github.com/boegel/easybuild-framework/archive/fd142036749d30e7f088e0f84eaff9cb0929ff50.tar.gz#egg=easybuild-framework
Processing fd142036749d30e7f088e0f84eaff9cb0929ff50.tar.gz
Writing /tmp/easy_install-O9WxFg/easybuild-framework-fd142036749d30e7f088e0f84eaff9cb0929ff50/setup.cfg
Running easybuild-framework-fd142036749d30e7f088e0f84eaff9cb0929ff50/setup.py -q bdist_egg --dist-dir /tmp/easy_install-O9WxFg/easybuild-framework-fd142036749d30e7f088e0f84eaff9cb0929ff50/egg-dist-tmp-wxJ567
Installing with setuptools.setup...
Installing version 2.0.0dev (API version 2)
Removing easybuild-framework 1.16.1 from easy-install.pth file
Adding easybuild-framework 2.0.0dev to easy-install.pth file
Installing eb script to /home/ward/opt/bin
Installing minimal_bash_completion.bash script to /home/ward/opt/bin
Installing optcomplete.bash script to /home/ward/opt/bin

Installed /home/ward/opt/lib/python2.7/site-packages/easybuild_framework-2.0.0dev-py2.7.egg
Processing dependencies for easybuild-framework==2.0.0dev
Searching for vsc-base>=2.0.0
Reading https://pypi.python.org/simple/vsc-base/
Best match: vsc-base 2.0.0
Downloading https://pypi.python.org/packages/source/v/vsc-base/vsc-base-2.0.0.tar.gz#md5=2212b1312fc6d9bdaf809d0134545875
Processing vsc-base-2.0.0.tar.gz
Writing /tmp/easy_install-6erPpx/vsc-base-2.0.0/setup.cfg
Running vsc-base-2.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6erPpx/vsc-base-2.0.0/egg-dist-tmp-lPWc_q
cleanup lib/vsc_base.egg-info
New target = {'maintainer': 'Stijn De Weirdt;Jens Timmermans;Andy Georges', 'name': 'vsc-base', 'author': 'Stijn De Weirdt;Jens Timmermans;Andy Georges', 'cmdclass': {'bdist_rpm': <class vsc.install.shared_setup.vsc_bdist_rpm at 0x7fbf4854d2c0>, 'egg_info': <class vsc.install.shared_setup.vsc_egg_info at 0x7fbf489d0a10>, 'install_scripts': <class vsc.install.shared_setup.vsc_install_scripts at 0x7fbf485326d0>}, 'download_url': 'https://github.com/hpcugent/vsc-base', 'maintainer_email': 'stijn.deweirdt@ugent.be;jens.timmermans@ugent.be;andy.georges@ugent.be', 'url': 'https://github.com/hpcugent/vsc-base', 'author_email': 'stijn.deweirdt@ugent.be;jens.timmermans@ugent.be;andy.georges@ugent.be', 'version': '2.0.0', 'scripts': ['bin/logdaemon.py', 'bin/startlogdaemon.sh', 'bin/bdist_rpm.sh', 'bin/optcomplete.bash'], 'install_requires': ['setuptools'], 'packages': ['vsc', 'vsc.utils', 'vsc.install'], 'package_dir': {'': 'lib'}}
looking for extra dist files
zip_safe flag not set; analyzing archive contents...
vsc.__init__: module references __path__
vsc.utils.missing: module references __path__
vsc.utils.generaloption: module MAY be using inspect.stack
vsc.utils.fancylogger: module MAY be using inspect.stack
Adding vsc-base 2.0.0 to easy-install.pth file
Installing bdist_rpm script to /home/ward/opt/bin
Installing startlogdaemon script to /home/ward/opt/bin
Installing logdaemon script to /home/ward/opt/bin
Installing optcomplete.bash script to /home/ward/opt/bin

Installed /home/ward/opt/lib/python2.7/site-packages/vsc_base-2.0.0-py2.7.egg
Finished processing dependencies for easybuild-framework==2.0.0dev
```
Seems fine?

**Comment by boegel** [comment]
Looks good, yeah. I'll look into making the bootstrap more flexible, so we can retest bootstrapping without actually releasing first (that's something I need to do anyway).

But since the bootstrap uses `easy_install`, that should be fine too.

**Comment by boegel** [comment]
enhanced bootstrap script that allows to bootstrap from provided tarballs is available in #1184, testing this branch with that script didn't reveal any problems (as expected), so I'm merging in this beast

thanks for reviewing @stdweird, @wpoely86!

**Pull request merged**
