### PR TITLE
add support for extracting .iso files using 7z (p7zip)

### PR DESCRIPTION
**Pull request by boegel**
see also http://unix.stackexchange.com/a/70740

### CODE REVIEW

**Comment by wpoely86** [comment]
looks fine

**Comment by fgeorgatos** [comment]
thanks about this; fyi. we were considering this issue while working back then for MATLAB PRs
* https://github.com/hpcugent/easybuild-easyconfigs/pull/233
* https://github.com/hpcugent/easybuild-easyconfigs/pull/234
will dig some more info and pass it along...

**Comment by boegel** [comment]
Works as intended.

I did run into this problem: https://github.com/hpcugent/easybuild-framework/issues/1376, but that's out of scope for this PR.

Thanks for the review @wpoely86 & @fgeorgatos!

**Comment by fgeorgatos** [comment]
for the record: 
it would be great to consider how this can be generalized, 
fi. invoke bsdtar in certain other systems or expand that logic for future archivers/decompressors etc...

**Pull request merged**
