### PR TITLE
support overriding # used cores via --parallel

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@sluehrs: I think you requested this?

**Comment by boegel** [comment]
@JensTimmerman: please review?

**Comment by sluehrs** [comment]
@boegel: Thank you very much for the fast commit.

**Comment by JensTimmerman** [comment]
ok

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins is getting very confused on this, grr...

**Comment by boegel** [comment]
Ah, Jenkins finally came to it's senses.

Going in, thanks for the review @JensTimmerman, and @sluehrs for making the feature request!

More control over what EasyBuild does is always good imho.

**Comment by JensTimmerman** [comment]
our jenkins is running up against the rate limiting for github api requests. We should look into configuring it to use a token so the limit is raised way up. If you run into this, you should at least wait till the hour rolls over, this is when the rate limits are reset.

**Pull request merged**
