### PR TITLE
fix bootstrap script for environment where 'python' is Python 3.x

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
@wpoely86: please review (successful test report coming up, I enhanced the PR tester to also check the bootstrap under `python2.7`)

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Going in, thanks @wpoely86!

**Pull request merged**
