### PR TITLE
fix extracting of comments from an easyconfig file that includes 'tail' comments

### PR DESCRIPTION
**Pull request by boegel**
fix for #1380

### CODE REVIEW

**Comment by boegel** [comment]
@JackPerdue: can you try applying this patch on top of EasyBuild v2.3.0 and confirm (or debunk) the fix?

An actual patch file is available via https://github.com/hpcugent/easybuild-framework/pull/1381.patch if that makes it easier for you.

**Comment by JackPerdue** [comment]
Much better... it didn't fall on its face and it even kept my comment in the log. :)
<pre>
# Built with EasyBuild version 2.3.0 on 2015-09-03_15-43-49
name = 'Python'
version = '2.7.10'
versionsuffix = '-bare'

homepage = 'http://python.org/'
description = "Python is a programming language that lets you work more quickly and integrate your systems more effectively."

toolchain = {'name': 'intel', 'version': '2015B'}
toolchainopts = {'pic': True, 'opt': True, 'optarch': True}

numpyversion = '1.9.2'
scipyversion = '0.15.1'

source_urls = ['http://www.python.org/ftp/%(namelower)s/%(version)s/']
sources = [SOURCE_TGZ]

# python needs bzip2 to build the bz2 package
dependencies = [
    ('bzip2', '1.0.6'),
    ('zlib', '1.2.8'),
    ('libreadline', '6.3'),
    ('ncurses', '5.9'),
    # openssl via RPM
]

osdependencies = [('openssl-devel', 'libssl-dev', 'libopenssl-devel')]

# bare installation: no extensions included
exts_list = []

moduleclass = 'lang'
#  EOF

# Build statistics
buildstats = [{
    "easybuild-framework_version": "2.3.0",
    "easybuild-easyblocks_version": "2.3.0",
    "timestamp": 1441313028,
    "build_time": 258.98,
    "install_size": 101993688,
    "command_line": ['--buildpath=/tmp/easybuild', '--deprecated=2.0', '--installpath=/software/easybuild', '--modules-tool=Lmod', '--packagepath=/software/easybuild/packages', '--prefix=/software/easybuild', '--repositorypath=/software/easybuild/ebfiles_repo/ada', '--robot=/software/easybuild/ebfiles_repo_cleaned/ada:/software/easybuild/software/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_easyconfigs-2.3.0-py2.6.egg/easybuild/easyconfigs', '--robot-paths=/software/easybuild/ebfiles_repo_cleaned/ada:', '--sourcepath=/software/easybuild/sources', 'Python-2.7.10-intel-2015B-bare.eb'],
    "modules_tool": ('Lmod', '/software/lmod/5.9.3/libexec/lmod', '5.9.3'),
    "core_count": 20,
    "cpu_model": "Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz",
    "cpu_speed": 2501.0,
    "cpu_vendor": "Intel",
    "gcc_version": "Using built-in specs.; COLLECT_GCC=gcc; COLLECT_LTO_WRAPPER=/general/software/x86_64/easybuild/software/GCC/4.8.4/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.8.4/lto-wrapper; Target: x86_64-unknown-linux-gnu; Configured with: ../configure --enable-languages=c,c++,fortran --enable-lto --enable-checking=release --disable-multilib --enable-shared=yes --enable-static=yes --enable-threads=posix --enable-gold=default --enable-plugins --enable-ld --with-plugin-ld=ld.gold --enable-bootstrap --prefix=/software/easybuild/software/GCC/4.8.4 --with-local-prefix=/software/easybuild/software/GCC/4.8.4; Thread model: posix; gcc version 4.8.4 (GCC) ; ",
    "glibc_version": "2.12",
    "hostname": "login2",
    "os_name": "centos",
    "os_type": "Linux",
    "os_version": "6.6",
    "platform_name": "x86_64-unknown-linux",
    "python_version": "2.6.6 (r266:84292, Jan 22 2014, 09:42:36) ; [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]",
    "system_gcc_path": "/software/easybuild/software/GCC/4.8.4/bin/gcc",
    "system_python_path": "/usr/bin/python",
}]
</pre>

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by boegel** [comment]
@JackPerdue: thanks for testing the fix!

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Thanks for the review @wpoely86, and @JackPerdue for confirming the fix! Going in...

**Pull request merged**
