### PR TITLE
fix HierarchicalMNS for CUDA with iccifort, push comp_versions definition out of for loop

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by thiell** [comment]
Hi there,

Any updates on this?

First I got a build error with the latest CUDA easyconfig (with GCC). Please check https://github.com/hpcugent/easybuild-easyconfigs/pull/2039
The function referenced there doesn't look so clean to me. Testing aside, not sure how I can help to improve this. Please advise :)

Second, @geimer your discussion whereas CUDA should introduce its own hierarchy level is interesting. Any update on this too since your comment? I'm not sure what's the best there. And I guess GCC is always needed in any case.

**Comment by ocaisa** [comment]
I'm interested in this discussion too, our new GPUs come online at the end of the month. I think I might get @damianam to follow this up at the hackathon next month. Maybe @geimer , he and I can have a preparatory discussion about it next week.

**Comment by geimer** [comment]
@thiell: I don't know much about CUDA and how it's being used (don't use it myself).  However, I still believe that the current scheme of handling it is seriously broken.  If it's all about a CUDA-enabled MPI, then there should simply be a separate MPI installation with some specific versionsuffix. This should simplify things a lot.

**Comment by damianam** [comment]
@geimer: if I understand the problem correctly, I am not sure the solution would be that simple. I think your proposal makes sense, as long as there is an GPU-aware MPI implementation already installed. For instance, having a toolchain with MVAPICH, and simply adding an MVAPICH-CUDA to that toolchain.

The problem as I see it now (and take my opinion for what is worth, keeping in mind that I am not an easybuild or CUDA expert) is that having a GPU-aware MPI implementation might require a different MPI than what you already have (Intel MPI, Platform MPI, MPICH, ParaStationMPI, ...), since these MPIs do not have a GPU-aware version. In that situation, you either create a new toolchain, you create an ugly "addon" to the existing toolchain that replaces one of the core elements (the MPI implementation), or you modify the concept of toolchain to discard the MPI component. None of these options look optimal to me.

Besides that a GPU-aware MPI user will want a CUDA capable compiler. So, even if you have a toolchain with MVAPICH, you might require a separate one if for instance your current toolchain has the Intel compiler and MVAPICH.

Most probably I am missing or misunderstanding something, but this looks like a worthy discussion.

**Comment by boegel** [comment]
@damianam: do you have a better view on this now?

**Comment by damianam** [comment]
@boegel: I do. But I am not quite sure why you are asking :-?

**Comment by boegel** [comment]
@damianam: well, this pull request is still open, and I was checking whether it could make it in for EB v2.4.0... That's very unlikely now though.

**Comment by damianam** [comment]
@boegel I guess it makes sense to ask also the others, I was the last one to join the conversation and I am not involved in the PR.

**Comment by boegel** [comment]
This is going to have to wait until 2.6.0 or later, so I'm moving the milestone on this one.

@geimer, @thiell, @ocaisa and others: what's our current view on all of this?

**Comment by ocaisa** [comment]
Hmm, this is a similar problem to what we faced before with iccifort on top of GCC and building an MPI implementation with the same name in for both GCC and iccifort. In  an HMNS you have another reverse race condition, whomever gets loaded last wins and you can easily end up with unpredictable behaviour. 
I don't see a ton of options in how to deal with this. To avoid it you'd have to version-suffix everything that actually gets built with iccifort+CUDA so it doesn't step on the toes of the same software built with iccifort...and if you were going to versionsuffix it anyway then why bother extending the path in another direction. 
Another option is to consider iccifort+CUDA as an alternative iccifort version (with a versionsuffix to indicate this), that would mean CUDA would have to come from the GCCcore level and we'd need the logic in the toolchain to pick up the existence of the CUDA dep and only use the CUDA class when it exists. Not sure if that one is feasible in the framework but you could repeat the same logic for GCC and PGI too.

I think this is worth having a long chat about at the user meeting, it's a very important issue for us right now.

**Comment by fgeorgatos** [comment]
my £0.02 view on the subject (which may or may not fit other people's
requirements):
Ideally, you'd like to be able to swap together toolchains, of any of the
following type:
- goolf/1.4.10 vs goolfc/1.4.10
or
- goolf/1.4.10 vs goolf/1.4.10-cuda # interesting offer, it could work for
some.

IMHO, when you get to complicated situations like this,
toolchains makes more sense at the 2nd level of hierarchy, rather than the
MPI stack
(fi. think: what about if a toolchain has multinode CUDA-MPI integration or
just CUDA)
first level could be either compilers (to differentiate) or, buildset (&
architecture) definitions.

**Comment by thiell** [comment]
A CUDA-aware MPI stack allows GPUDirect to be directly supported by the MPI stack (http://devblogs.nvidia.com/parallelforall/introduction-cuda-aware-mpi/). I think in that case you can suffix the MPI version with a specific CUDA version.

At my site, we're mainly using a non CUDA-aware MPI stack (so a standard toolchain) but with installed software depending on a specific version of CUDA (so we should use versionsuffix here at the software level). We have big fat GPU nodes to avoid the use of GPUDirect (still it may be something we'll look at soon).

To be honest, I recently worked on new easyblocks/easyconfigs and actually I didn't add any CUDA versionsuffix yet, so CUDA is loaded under the hood.  Also the problem of a CUDA aware MPI stack, is that you're stuck with a specific version of CUDA, and we have software requiring 6.5, but other 7.0 and we also provide 7.5 which is mostly for new developments as it breaks many existing software... that would mean at least creating new 3 toolchains.

It really seems like a complex problem, at least for me (I'm just an easybuild user). Maybe a system based on tags instead of static toolchains could be a nice future improvement, I mean something more flexible for the compiler/MPI/CUDA/Python/etc. dependencies...

**Comment by fgeorgatos** [comment]
@thiell, all: that's an interesting take;

is there any way to break the chain between MPI stack and CUDA stack?
(you could do a `module swap CUDA` after the loads, and cross fingers that
dynamic linking would help it; sounds hackish though; the answer to this
question might give insight, as regards the preferred naming design)


On 14 December 2015 at 18:18, thiell <notifications@github.com> wrote:

> A CUDA-aware MPI stack allows GPUDirect to be directly supported by the
> MPI stack (
> http://devblogs.nvidia.com/parallelforall/introduction-cuda-aware-mpi/).
> I think in that case you can suffix the MPI version with a specific CUDA
> version.
>
> At my site, we're mainly using a non CUDA-aware MPI stack (so a standard
> toolchain) but with installed software depending on a specific version of
> CUDA (so we should use versionsuffix here at the software level). We have
> big fat GPU nodes to avoid the use of GPUDirect (still it may be something
> we'll look at soon).
>
> To be honest, I recently worked on new easyblocks/easyconfigs and actually
> I didn't add any CUDA versionsuffix yet, so CUDA is loaded under the hood.
> Also the problem of a CUDA aware MPI stack, is that you're stuck with a
> specific version of CUDA, and we have software requiring 6.5, but other 7.0
> and we also provide 7.5 which is mostly for new developments as it breaks
> many existing software... that would mean at least creating new 3
> toolchains.
>
> It really seems like a complex problem, at least for me (I'm just an
> easybuild user). Maybe a system based on tags instead of static toolchains
> could be a nice future improvement, I mean something more flexible for the
> compiler/MPI/CUDA/Python/etc. dependencies...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hpcugent/easybuild-framework/pull/1086#issuecomment-164515738>
> .
>



-- 


echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by thiell** [comment]
@fgeorgatos: oh that sounds hackish indeed. :) I don't have the answer, sorry. MPI aside, I can just tell you that when a binary is compiled with a specific version of CUDA (with nvcc), you cannot dynamically swap the cuda library in case of a major change, as it links to cudart.so.7.0 for instance for cuda 7.0.28.

**Comment by ocaisa** [comment]
I too wonder how much value there is in having CUDA as anything other than a dependency at the moment. There's nothing in EB (yet) that uses it as a toolchain far as I can tell. 

For most of the software I've seen it just seems to be a matter of having nvcc available and maybe telling the software where you can find the installation. I definitely see the problem with needing multiple CUDA versions, we only have 7.5 at the moment, but we have people asking us to install 5.5 which I'm resisting.

We do have a plan for toolchains with MVAPICH2-GDR and that's where our CUDA-based branching is being targeted, but for those  who don't need the extra performance that this might provide, we're providing CUDA as a normal package with all our compilers. Applications that we build within EB and require CUDA will be within the toolchain with MVAPICH2-GDR because we will probably want to start leveraging EB within the build procedures (though the value of this is still not clear since all the build triggers for CUDA seem pretty ad-hoc).

**Comment by boegel** [comment]
This is now totally obsolete since #1986 is merged.

**Pull request closed without merging**
