### PR TITLE
Add support for 'hidden=True' easyconfig parameter

### PR DESCRIPTION
**Pull request by geimer**
This complements the '--hidden' command-line option.

### CODE REVIEW

**Comment by boegel** [comment]
@geimer: `build_option('hidden')` is also used in `process_easyconfig`, do we need to check the `hidden` parameter there too?

Looks tricky at first sight, since it's used before parsing the easyconfig, and I'm not sure it's strictly needed there...

**Comment by geimer** [comment]
@boegel: Something like `hidden = hidden or ec['hidden']` in the `if not parse_only:` block may do the trick.  What do you think?

**Comment by geimer** [comment]
Of course I meant `easyconfig['hidden']` instead of `ec['hidden']` ;-)

**Comment by geimer** [comment]
@boegel: I believe the easyconfig update for `hidden` in L1230 isn't necessary. The `build_option` is passed to the `EasyConfig` constructor, which will correctly initialize the value based on `build_option` and the `hidden` easyconfig parameter.  Does that make sense?

**Comment by geimer** [comment]
@boegel: Still trying to understand the code...

Shouldn't the update in https://github.com/geimer/easybuild-framework/blob/5d9a56a543eb7f8e078d6aa737077cfc23be40ed/easybuild/framework/easyconfig/easyconfig.py#L1230 be `'hidden': ec.hidden`?  Then the first query to `build_option('hidden')` only affects the cache lookup, which should be OK as the data in the cache should already include parsed values.  The update then takes the actual parsed value into account, determined in the `EasyConfig` constructor based on the build option and the easyconfig parameter.

The thing is that the `easyconfig` unit tests all pass, regardless of what the update does.  I can even hard-code it to `True` or `False`...

BTW: There is a docstring for the `parse_only` parameter missing.

**Comment by boegel** [comment]
@geimer I think you're right with your last comment. Up until now it didn't really matter, but with the introduction of the `hidden` easyconfig parameter, it does matter.

I'd have to dive in and figure out where that `'hidden'` key is actually used, if at all, it may be "dead code", but it certainly doesn't hurt to get it right (and using `ec.hidden` is correct imho).

The cache aspect is a bit weird, but only taking into account `--hidden` in the cache key is correct imho, since the `hidden` easyconfig parameter only comes into play when the easyconfig is already parsed.

**Comment by geimer** [comment]
@boegel: IMHO, this is ready for review.

**Comment by boegel** [comment]
@geimer looks good, but I couldn't resist making a few minor tweaks, see https://github.com/geimer/easybuild-framework/pull/8

**Comment by boegel** [comment]
Going in, thanks @geimer!

**Pull request merged**
