### PR TITLE
fix availability check for external modules with partial module name

### PR DESCRIPTION
**Pull request by boegel**
required to make `--robot --from-pr` work on https://github.com/hpcugent/easybuild-easyconfigs/pull/2554

without this, you run into this:

```
kehoste@daint102:~> eb --from-pr 2554 -dfr
== temporary log file in case of crash /tmp/eb-SCGaNv/easybuild-nBdPrL.log
== resolving dependencies ...
ERROR: Missing modules for one or more dependencies marked as external modules: ['PrgEnv-gnu', 'PrgEnv-gnu', 'PrgEnv-cray', 'PrgEnv-cray', 'PrgEnv-intel', 'PrgEnv-intel']
```

### CODE REVIEW

**Comment by boegel** [comment]
cc @pforai, @gppezzi

**Comment by wpoely86** [comment]
So the check is now independent whether it's hidden or not? lgtm

**Comment by boegel** [comment]
@wpoely86: yes, it basically fall backs to checking with `module show` in case the exact module name is not listed in the output of `module avail`

This occurs for hidden modules (e.g. `.foo/1.2.3`) and external modules with a partial module name (e.g. checking if `PrgEnv-gnu` is available, while `avail` spits out `PrgEnv-gnu/5.2.40`).

There's no harm in always falling back to `show`, except for maybe making things slower (`modtool.exist` will also check via `avail` first).

Maybe I should add an extra named argument to `modtool.exist` to specify that it should skip the `avail` check?

**Comment by boegel** [comment]
@wpoely86: done, please rereview? Using `skip_avail=True` makes sense anywhere where only a single module name is provided (`show` is likely faster than `avail` in the case)

**Comment by gppezzi** [comment]
I confirm that this PR is working (see reports on https://github.com/hpcugent/easybuild-easyconfigs/pull/2554)

thx @boegel

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Going in, thanks for the review @wpoely86 and feedback @gppezzi!

**Pull request merged**
