### PR TITLE
avoid copying patch to itself, replace use of shutil.copy/copy2 with copy_file

### PR DESCRIPTION
**Pull request by boegel**
fix for #2237 + some refactoring

### CODE REVIEW

**Comment by boegel** [comment]
@vanzod please review?

**Comment by vanzod** [comment]
Good job. Why not moving the `if` blocks in the `copy_file` function?

**Comment by boegel** [comment]
@vanzod Hah, yeah, good point! I'll look into that...

**Comment by boegel** [comment]
@vanzod please rereview?

**Comment by vanzod** [comment]
lgtm

**Comment by boegel** [comment]
Thanks for the review @vanzod!

**Pull request merged**
