### PR TITLE
 Use different logger classes depending on prefix of requested logger

### PR DESCRIPTION
**Pull request by riccardomurri**
As the title says: this allows external libraries (e.g., GC3Pie) to use stdlib logging, while EB continues to use its own logging facility.

It's a hack, however, that involves directly setting a module-level private variable...

### CODE REVIEW

**Comment by riccardomurri** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Things are very broken now, it seems... Somehow EasyBuild isn't using an EasyBuildLog instance anymore?

```
Traceback (most recent call last):
  File "test/framework/options.py", line 1065, in test_deprecated
    log.deprecated('x', str(orig_value))
TypeError: deprecated() takes at least 4 arguments (3 given)
```

```
Traceback (most recent call last):
  File "test/framework/options.py", line 1028, in test_experimental
    log.experimental('x')
AttributeError: FancyLogger instance has no attribute 'experimental'
```

```
Traceback (most recent call last):
  File "test/framework/easyconfigparser.py", line 75, in test_v20
    ec = ecp.get_config_dict()
  File "easybuild/framework/easyconfig/parser.py", line 148, in get_config_dict
    return self._formatter.get_config_dict()
  File "easybuild/framework/easyconfig/format/two.py", line 99, in get_config_dict
    self.log.experimental(self.__class__.__name__)
AttributeError: FancyLogger instance has no attribute 'experimental'
```

**Comment by riccardomurri** [comment]
@boegel Fixed now, thanks for the heads-up.

**Comment by riccardomurri** [comment]
A lighter-weight alternative to this is in #1179

**Comment by boegel** [comment]
same here as in #1179; this is a very complex workaround while https://github.com/hpcugent/easybuild-framework/pull/1008/files#diff-30c0c724e8b33847f917f22eca0af7a0R57 does the trick as well, and the `raiseError` aspect of `EasyBuildLog` has been deprecated (to disappear in EB v3.0), so this is no longer useful?

**Comment by riccardomurri** [comment]
Yes, I agree to closing w/out merging

**Pull request closed without merging**
