### PR TITLE
Add ability to clear toolchain cache

### PR DESCRIPTION
**Pull request by ocaisa**

### CODE REVIEW

**Comment by ocaisa** [comment]
Can now use `get_toolchain_hierarchy.clear()` to empty the cache

**Comment by boegel** [comment]
@ocaisa: duplicate of #1619?

**Comment by ocaisa** [comment]
Yup, merged there, closing

**Comment by boegel** [comment]
@ocaisa: why reopen?

**Comment by ocaisa** [comment]
Ah I just added the cache clearing and want Jenkins to check if it was working...curiosity

**Comment by ocaisa** [comment]
And it works ;)

**Pull request closed without merging**
