### PR TITLE
Fix --set-default-module flag

### PR DESCRIPTION
**Pull request by victorusu**
Now, modules with prefix and suffix versions can be set as default

### CODE REVIEW

**Comment by boegel** [comment]
@victorusu Can we enhance the tests to make sure the bug you fixed here doesn't get reintroduced?

**Comment by boegel** [comment]
@victorusu psst, always target `develop` for PRs (I know, it's easy to overlook); I've changed the target branch just now

**Comment by boegel** [comment]
@victorusu Test added in https://github.com/victorusu/easybuild-framework/pull/2, please review/merge that PR to make this PR good to go?

**Comment by victorusu** [comment]
I merged the test. And I think it is good to go! Thanks @boegel!

**Comment by boegel** [comment]
Going in, thanks for the fix @victorusu!

**Pull request merged**
