### PR TITLE
respect --suffix-modules-path value for user-specific module path extensions

### PR DESCRIPTION
**Pull request by ocaisa**

### CODE REVIEW

**Comment by ocaisa** [comment]
Fixes the issue mentioned at the end of #1472

**Comment by ocaisa** [comment]
I can answer for @geimer, yes he uses `EASYBUILD_SUFFIX_MODULES_PATH=''`

**Comment by geimer** [comment]
@boegel Yes, I've always used `EASYBUILD_SUFFIX_MODULES_PATH=''` as the `all` suffix never made any sense to me.  IMHO, the empty string should actually be the default.

**Comment by boegel** [comment]
@geimer Thanks for the confirmation, that explains why this went unnoticed.

Using `''` as default for `--suffix-modules-path` wouldn't work because EasyBuild by default also creates subdirectories for each `moduleclass`...
Let's consider it a historical mistake, any default will only make sense for some sites.

**Comment by ocaisa** [comment]
Ok, looks like the tests pass now.

**Comment by boegel** [comment]
The changes look good, but it raises a question...

Say EasyBuild is configured with `--suffix-modules-path=all` for the centrally installed modules, but the user configures EasyBuild differently, for example with `--suffix-modules-path=''` like @geimer is doing.

Should that be a concern? If so, than we need a separate `--suffix-modules-path-user`?

**Comment by geimer** [comment]
@boegel Better leave this can of worms closed...  What if the user prefers to use a flat naming scheme but the system-wide install uses HMNS?  You see my point?

**Comment by ocaisa** [comment]
The user does have control over what suffix they use (since it is their own instance of `--suffix-modules-path` that will create the path) but the system just has to chose some default (@geimer chooses `''`, the EB default is `all` but the choice is system specific) since it cannot handle the infinite options open to the end user. As long as the sys-admin is the one preparing the module that sets up their EB environment this is not an issue...and even if they are not it is still fixable by the end user by choosing an appropriate `--suffix-modules-path`

**Comment by ocaisa** [comment]
Tests passing, good to go

**Comment by boegel** [comment]
@geimer Well, mixing different types of naming schemes is a whole different matter, since you just can't make that work at all.

@ocaisa I'm mainly worried about changing the default behaviour... In EasyBuild v3.3.0, you would never get a suffix for the module path, now you get `'all'` by default.

I think others besides @geimer are using this too (do you happen to know who, @geimer)?

But, since it's a bug fix we can probably get away with clearly mentioning this in the release notes?

**Comment by ocaisa** [comment]
I see where you are coming from, but the previous behaviour forced you to explicitly move away from EasyBuild default behaviour for the user (they *must* use `--suffix-modules-path=""` or it doesn't work properly). If the system default is `--suffix-modules-path=""` (which I know is true for both @geimer and @akesandgren), then this will not change the behaviour for them at all.

**Comment by boegel** [comment]
@ocaisa Good point. So, let's merge!

Thanks for the fix @ocaisa, and @geimer for the feedback!

**Pull request merged**
