### PR TITLE
Drop dead code and fix bug (not using --job-cores in pbs_python)

### PR DESCRIPTION
**Pull request by wpoely86**
The decorator gets executed in _check_version

### CODE REVIEW

**Comment by boegel** [comment]
lgtm, is this related to #1523 at all?

**Comment by wpoely86** [comment]
Yes, I discovered this on the road to fixing #1523

**Comment by wpoely86** [comment]
@boegel I've pushed the fix for #1523 also here as it's quite small.

**Comment by boegel** [comment]
@wpoely86: please update PR title to reflect that?

**Comment by wpoely86** [comment]
@boegel ready to merge. Tested with our PBS systems and it works. I didn't test gc3pie.

**Comment by boegel** [comment]
Please test GC3Pie too? Can we enhance the unit tests, so we catch this if it occurs again in the future (`--job-cores` not being passed down properly, that is)

**Comment by wpoely86** [comment]
The unit tests are already extended

**Comment by wpoely86** [comment]
@boegel GC3Pie works too.

**Comment by boegel** [comment]
Thanks @wpoely86!

**Pull request merged**
