### PR TITLE
isolate unit tests from available easyblocks other than those included in the tests

### PR DESCRIPTION
**Pull request by boegel**
fix for #1195 

@JensTimmerman, @pforai: please review

### CODE REVIEW

**Comment by JensTimmerman** [comment]
can't we just do local imports now to import the correct file?

**Comment by boegel** [comment]
no, this change is required to for example isolate the test for `--list-easyblocks` from easyblocks other than the ones included in the tests themselves

we want to test the functionality that supports `--list-easyblocks`, not whether the easyblocks we happen to pick up have no syntax errors...

**Comment by JensTimmerman** [comment]
ok

**Comment by boegel** [comment]
Thanks @JensTimmerman!

**Pull request merged**
