### PR TITLE
take into account possible multi-line modloadmsg in ModuleGeneratorLua

### PR DESCRIPTION
**Pull request by boegel**
fix for problem reported at https://github.com/hpcugent/easybuild-framework/issues/1067#issuecomment-241713966

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86 please review

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
@wpoely86 I had to flesh this out a bit further, since multi-line prints in Lua modules require Lmod 5.8 or newer (and we claim that Lmod 5.6.3 suffices in general)

please rereview?

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
