### PR TITLE
add support for %(pyver)s and %(pyshortver)s templates

### PR DESCRIPTION
**Pull request by boegel**
fix for #1594

### CODE REVIEW

**Comment by pescobar** [comment]
great! thanks for the quick patch :+1: 

may I suggest ```perlver``` and ```Rver``` templates? :)  see:

https://github.com/hpcugent/easybuild-easyconfigs/search?utf8=%E2%9C%93&q=perlver
https://github.com/hpcugent/easybuild-easyconfigs/search?utf8=%E2%9C%93&q=Rver

**Comment by boegel** [comment]
@pescobar: done! Also fixed the breakage of tests, and updated the 'docs':

```
$ eb --avail-easyconfig-templates | grep -B 1 ver:                                                   
Template names/values for (short) software versions
    perlver: full version for Perl
    perlshortver: short version for Perl (<major>.<minor>)
    pyver: full version for Python
    pyshortver: short version for Python (<major>.<minor>)
    rver: full version for R
    rshortver: short version for R (<major>.<minor>)
```

**Comment by wpoely86** [comment]
lgtm but another test needs fixing because of the changes to the tests.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Thanks for the review @wpoely86, and @pescobar for the idea/suggestion! Going in...

**Pull request merged**
