### PR TITLE
POWER: Fix `--optarch=GENERIC` for GCC

### PR DESCRIPTION
**Pull request by geimer**
Fixes https://github.com/hpcugent/easybuild-framework/issues/2064

Note that this PR builds on top of ~~https://github.com/hpcugent/easybuild-framework/pull/1974~~ (the diff will get lean and mean once ~~https://github.com/hpcugent/easybuild-framework/pull/1974~~ is merged)

### CODE REVIEW

**Comment by geimer** [comment]
With this branch, I was able to robot-build `HPL-2.1-foss-2016b.eb` on our BG/Q frontend (POWER7) with `EASYBUILD_OPTARCH=GENERIC` set in the environment.  I only had to tweak the FFTW easyconfig a bit (due to the hardcoded `--enable-sse2` configure option and a missing `libquadmath`).  The resulting `xhpl` binary ran fine, though I don't have the possibility to test whether it would also run on a different POWER-based system (i.e., whether it is "generic").

**Comment by boegel** [comment]
@geimer please sync with `develop` now that #1974 is merged?

Seems like you'll also need to deal with a merge conflict in `systemtools.py`...

**Comment by geimer** [comment]
@boegel: Synced.  And git didn't report any conflicts...

**Comment by boegel** [comment]
@geimer OK, great. GitHub mentioned there was a conflict, but I guess it just got confused.

**Comment by boegel** [comment]
@JackPerdue Can you take a look at these changes, and provide some feedback?

Looks good to me, but this may impact you (even though the changes look backwards-compatible to me).

**Comment by JackPerdue** [comment]
A quick test:
gcc -mcpu=native hello.c
gcc -mcpu=powerpc64 hello.c
xlc -qtune=auto -qmaxmem=1 hello.c
all work on our Power7 cluster (our BG/Q is gone).

I didn't do a full test with EB, but it looks good to me at this point..

**Comment by boegel** [comment]
OK, thanks for the feedback @JackPerdue!

I see no reason to hold this back any further, thanks a lot for tackling this @geimer, going in!

**Pull request merged**
