### PR TITLE
check whether dependencies marked as external module are hidden

### PR DESCRIPTION
**Pull request by boegel**
fixes issue reported in https://github.com/hpcugent/easybuild/issues/185

@DirkDeDraak: can you check whether the problem you reported is fixed with this patch (which is a better place to handle it than the patch you proposed imho)?

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
lgtm

**Comment by wpoely86** [comment]
Maybe add test? :smiling_imp:

**Comment by boegel** [comment]
@wpoely86: unit test (case) added

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

@DirkDeDraak: do keep us posted whether this solves the problem you reported

**Pull request merged**
