### PR TITLE
do not ignore exit code of failing postinstall commands

### PR DESCRIPTION
**Pull request by boegel**
issue uncovered by @pescobar 

@wpoely86: please review?

### CODE REVIEW

**Comment by wpoely86** [comment]
looks good!

**Comment by wpoely86** [comment]
Fix is OK for this problem but when run in debug mode, the return code of `run_cmd` should always be logged. See https://github.com/hpcugent/easybuild-framework/blob/master/easybuild/tools/run.py#L379

**Comment by boegel** [comment]
@wpoely86: fixed the logging issue in `run_cmd`, thanks for pointing that out

**Comment by boegel** [comment]
going in, thanks @wpoely86 for the review!

**Pull request merged**
